name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: 👷🏻‍♀️ Build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm ci
      - name: 👷🏻‍♀️ Build
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    name: 🚀 Vercel Production Deployment
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.BACK_INVOICE_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.BACK_INVOICE_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.BACK_INVOICE_TOKEN }}
